version: "3"
services:
  keycloak-db:
    image: "postgres:latest"
    container_name: "keycloak-db"
    restart: always
    environment:
      POSTGRES_DB: "fofo"
      POSTGRES_USER: "fofo"
      POSTGRES_PASSWORD: "fofo"
    ports:
      - "9432:5432"
    volumes:
      - ./keycloak-db-data:/var/lib/postgresql/data
  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: "keycloak"
    restart: unless-stopped
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/fofo
      KC_DB_USERNAME: "fofo"
      KC_DB_PASSWORD: "fofo"
      KEYCLOAK_ADMIN: "fofo"
      KEYCLOAK_ADMIN_PASSWORD: "fofo"
    command:
      - start-dev
    ports:
      - "9090:8080"